### ISSUE TITLE
Ошибка при импорте слов из словарей LinguaLeo

### ISSUE THREAD

**Issue by commonlisper** [vi3itor/lingualeoanki#1]
При импорте показывает наличие старых слов в словарях на LinguaLeo, хотя их там давно нет, они были удалены. Но почему-то происходит их импорт.

**Comment by vi3itor** [comment]
Аддон не кеширует словари и слова, а каждый раз получает их от сервиса Lingualeo в формате json. Я думаю, что ваша проблема на стороне lingualeo, и связана со злосчастным обновлением от 30 апреля. Можете проверить на сайте lingualeo, видны ли эти слова и словари? И если нет, то попробуйте перейти по следующей ссылке в браузере: https://lingualeo.com/ru/userdict3/getWordSets - это для получения списка словарей, "countWords" подсказывает сколько слов в словаре. 

На всякий случай, проверил на своём аккаунте и попросил друзей - нас эта проблема не коснулась, все словари на месте, удалённых слов нет.

**Comment by commonlisper** [comment]
Зашел по ссылке, все та же проблема: несуществующие словари и слова. 
Точно проблема на стороне lingualeo.
