### ISSUE TITLE
Удаленные слова

### ISSUE THREAD

**Issue by alexeyboo** [vi3itor/lingualeoanki#10]
Будет ли возможность синхронизации того, что слова были удалены из словаря?

**Comment by vi3itor** [comment]
Это хороший вопрос... В идеале, хотелось бы иметь такую возможность: поддерживать актуальный список слов в веб-версии и периодически синхронизировать его с Анки при помощи расширения. Но учитывая, что они (LinguaLeo) до сих пор не могут оправиться от своего обновления от 29 апреля, постоянно экспериментируют с API и ломают совместимость - пользователи до сих пор жалуются, что многие слова потеряны, переводы кривые и т.д. - я пока что не буду добавлять эту задачу в очередь. 
Мне бы сейчас хотелось, чтобы они починили, всё что сломано, и больше не меняли API.
