### ISSUE TITLE
Error: ('must be str, not NoneType') when trying to Import all words

### ISSUE THREAD

**Issue by yaroslav-shlapak** [vi3itor/lingualeoanki#11]
![Screenshot from 2019-11-30 22-27-02](https://user-images.githubusercontent.com/3373419/69905736-999be200-13c0-11ea-9569-36b339889853.png)
It looks like some generic Python error. Please let me know if you need additional information.

**Comment by vi3itor** [comment]
It works fine on my Mac, but I will check tomorrow on the Ubuntu machine. What is your Anki version and what API did you try to use?

**Comment by yaroslav-shlapak** [comment]
- Anki version: Version 2.1.15 (442df9d6), Qt 5.12.1 PyQt 5.11.3
- New lingualeo api
- Ubuntu 18.04.3 LTS
- System version of Python: Python 3.7.5

I've just tested on my macbook, the add-on does work there. So yeah it's some system-related or Python version issue, on mac I have Python 2.7.16 as system version of Python.

**Comment by vi3itor** [comment]
I fixed the issue. Please update the add-on and let me know if you find any other errors. Thank you!
