### ISSUE TITLE
How long should it exlude existing words?

### ISSUE THREAD

**Issue by kpspu** [vi3itor/lingualeoanki#13]
I use an add-on for several Lingualeo Dictionaries with success.
Now I am trying to download all word bases. It is stuck on "Found 21897 words. Excluding already existing..." for about 4.5 hours. Is it normal? Should I wait, or is it an error?

**Comment by vi3itor** [comment]
Well, 21897 is probably a lot for Anki to process because it queries the database for each word. A possible solution: choose the "Update existing notes" option. It won't search for existing words then.

**Comment by kpspu** [comment]
Yes, I can download all base in 1-2 hours by choosing the option "Update existing notes". I was afraid it rewrote my existing notes in Anki with customized tags, but everything was fine.
There was a lot of error windows in Anki about some Python mistakes. If you don't close them immediately, they will crush Anki. So I sat near my Anki for 2 hours to close them. But it's another issue, and I didn't copy the error window.
Based on the above, I am closing this issue. Thank you for the excelent add-on! Don't live it! You helped me very much!
