### ISSUE TITLE
Lingualeo changed API, can't login

### ISSUE THREAD

**Issue by kpspu** [vi3itor/lingualeoanki#16]
I had a bad conversation with Lingualeo Support. They changed the link for a login today, but they didn't tell me the new one.
Can you find another way to log in?

My corresponding with Lingualeo:
Вячеслав, уточнили информацию по этому вопросу у наших специалистов.То, что Вы указали, это не наше расширение, а стороннее.Разработчики стороннего расширения использовали ссылку для логина, которую мы больше не используем.

**Comment by vi3itor** [comment]
Thanks for the report. I fixed it. 
I also temporarily disabled the Old API switch because it doesn't work as expected. But I'm planning to fix the downloading of the context in the upcoming days.
