### ISSUE TITLE
Не загружаются новые слова после обновления lingualeo от 30.04.2019

### ISSUE THREAD

**Issue by dante2288** [vi3itor/lingualeoanki#2]
Слова, добавленные в словарь lingualeo ПОСЛЕ обновления 30.04.2019, не загружаются плагином в anki, плагин их не видит. Все они в категории "unstudied". Слова, добавленные до обновления, подгружаются нормально (они тоже были в категории "unstudied").

**Comment by vi3itor** [comment]
Спасибо, я тоже недавно заметил, что не видит новых слов и новых наборов. Они, похоже, полностью забросили старый API. Пытаюсь найти решение (либо новый API).

**Comment by hior** [comment]
Попробовал новую версию, всё равно новых слов не видит почему-то

**Comment by vi3itor** [comment]
> Попробовал новую версию, всё равно новых слов не видит почему-то

Очень странно... Я попробовал на рабочем компьютере с Windows, на виртуальной машине и даже попросил друзей проверить - у всех работает (по крайней мере на Windows, как доберусь домой, перепроверю на Mac). 
Пожалуйста, попробуйте выполнить следующие шаги: 
1) Убедитесь, что после обновления дополнения, вы перезапустили Anki, так как изменения вступают в силу только после перезапуска.
2) Нажмите Log Out и снова сделайте Log In (чтобы обновить cookies, хотя должно работать и без этого). 
3) Если и это не помогло - попробуйте удалить дополнение и загрузить снова. 

И если после всех этих шагов у вас всё равно не видит новых слов и новых наборов, попробуйте, пожалуйста, если конечно не сложно, создать тестовый аккаунт на LinguaLeo и проверить, работает ли с ним, либо напишите мне на 4yourquestions (собачка) gmail.com и я пришлю вам тестовый логин и пароль. Спасибо.

**Comment by hior** [comment]
Да, помогла перезагрузка, не подумал об этом. Спасибо большое!

**Comment by vi3itor** [comment]
Отличные новости, спасибо! Обновлю инструкцию, так как сама Анки очень уж незаметно показывает сообщение, что изменения вступят в силу только после перезагрузки программы.
