### ISSUE TITLE
Customization of note type doesn't affect newly generated cards

### ISSUE THREAD

**Issue by Igggr** [vi3itor/lingualeoanki#22]
I wanted to add new field to generated cards, That card should be shown only when I press 'answer', no matter if I see 'front' or 'back' of the card. So I select "**Notes -> Manage note types -> linguoleo mode**l" and here I selected "**fields -> add**" and also "**cards**", where I added this field to template. For old cards it works as expected - new field appeared. But with new cards I get a problem

**expected behavior**: new cards generated with type Linguoleo_model (that I edited), fields added by me stays blank

**actual behavior**: new cards generated with type **Linguoleo_model_<random_suffix>**, Suffix differ each time. Field added by me is absent, I must change note type o Linguoleo_model manually and that also requires full database upload afterwards

Я хотел добавить новое поле к генерируемым карточкам. Оно должно было показываться только после нажатия кнопки "показать ответ", не зависимо от того, какую сторону карточки я видел ('front' или 'back'). 
Я пошел в "Notes -> Manage note types -> linguoleo model" и выбрал "fields -> add", а затем "cards", где и добавил это поле в шаблон. Со старыми карточками все прошло как надо - новое поле появилось. С генерацией новых однако возникла проблемма

**хотел**: новые карточки генерируются по измененному мной шаблону linguoleo model. Новое поле остается пустым

**получил**: новые карточки генерируются по старому шаблону. в котором нет добавленного мной поля. Его название **каждый раз разное** -  **Linguoleo_model_<random_suffix>**. Мне проиходится изменять тип карточки вручную, а это в свою очередь требует полной синхронизации с anki web.

**Comment by vi3itor** [comment]
Thanks for the report. I will check it out and get back to you.

**Comment by vi3itor** [comment]
Исправлено! Проверяйте.

**Comment by Igggr** [comment]
Спасибо, эта проблемма устранена
