### ISSUE TITLE
Error! POSSIBLY, INVALID DATE WAS RECIEVED FROM LINGUALEO

### ISSUE THREAD

**Issue by dashcats** [vi3itor/lingualeoanki#24]
Как решить эту проблему?или к кому обратиться?Заранее спасибо

**Comment by vi3itor** [comment]
@dashcats, LinguaLeo снова изменили API (в данном случае адрес для авторизации). Я уже решил проблему, но хотел внести ещё несколько исправлений, прежде чем выкладывать новую версию. Планирую сделать это завтра или послезавтра. Если нужно поскорее, то достаточно исправить адрес в строке 275 в файле `connect.py` с `'lingualeo.com/auth'`на `'lingualeo.com/api/auth'`.

**Comment by dashcats** [comment]
Спасибо большое! А ещё два вопроса 1.можно импортировать отдельно
немецкие,и  отдельно английские слова 2.можно импортировать с приложения на
телефоне,или  только с компьютера ?

сб, 18 июн. 2022 г., 17:25 Victor Khaustov ***@***.***>:

**Comment by vi3itor** [comment]
1. Аддон создавался в тот момент, когда был доступен для обучения только английский язык, но я могу попробовать добавить поддержку других языков, если будут желающие. 
2. Импортировать можно только с компьютера.

**Comment by vi3itor** [comment]
Сегодня я не смогу выложить новую версию, так как нужно ещё протестировать предупреждение пользователя о неподдерживаемой комбинации языков. Постараюсь закончить в ближайшие несколько дней.

**Comment by dashcats** [comment]
обновление уже доступно?не могу загрузить

**Comment by vi3itor** [comment]
> обновление уже доступно?не могу загрузить

К сожалению, последние две недели оказались довольно загруженными. Постараюсь выложить обновление завтра.

**Comment by vi3itor** [comment]
Наконец-то получилось закончить с обновлением. Проблема авторизации решена, контекст также загружается. Проверьте, пожалуйста, и сообщите, если возникнут ошибки. 

Пока что по-прежнему работает только с английским языком, но если подвернётся ещё один свободный вечер, то добавлю поддержку остальных языков: уже нашёл соответствующие API функции, осталось исправить существующий код.

**Comment by dashcats** [comment]
Спасибо большое!! Все работает!:)

**Comment by vi3itor** [comment]
Отлично!
