### ISSUE TITLE
I've got error trying to import 

### ISSUE THREAD

**Issue by vbutaev** [vi3itor/lingualeoanki#3]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.13 (3ba55990) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 7
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1411073333\connect.py", line 262, in run
    self.add_separately()
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1411073333\connect.py", line 277, in add_separately
    utils.send_to_download(word, self)
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1411073333\utils.py", line 106, in send_to_download
    pictures = word['trs'][0]['pics']
<class 'TypeError'>: 'NoneType' object is not subscriptable
Caught exception:
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1411073333\gui.py", line 318, in addWord
    utils.add_word(word, self.model)
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1411073333\utils.py", line 166, in add_word
    note = fill_note(word, note)
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1411073333\utils.py", line 141, in fill_note
    translation = word['trs'][0]
<class 'TypeError'>: 'NoneType' object is not subscriptable

**Comment by vi3itor** [comment]
@vbutaev Спасибо, попробую исправить. А может догадываетесь на каком слове произошла ошибка? Судя по ошибке у слова (или фразы) нет перевода.

**Comment by vbutaev** [comment]
к сожалению нет, их более 4000, если можно поискать как-то по номеру карточки на лео (1411073333 это же она?) то проще исправить ее, конечно

**Comment by vi3itor** [comment]
1411073333 - это название папки, в которой лежит дополнение. 
Ничего страшного, я попробую быстрый фикс - проверим, как будет работать.

**Comment by vbutaev** [comment]
спасибо за быстрый ответ, было бы очень здорово

**Comment by vi3itor** [comment]
Я залил новую версию. Попробуйте обновиться, перезапустите Anki, и отпишитесь, будут ли сообщения об ошибке. Спасибо!

**Comment by vbutaev** [comment]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.13 (3ba55990) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 7
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1411073333\connect.py", line 262, in run
    self.add_separately()
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1411073333\connect.py", line 277, in add_separately
    utils.send_to_download(word, self)
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1411073333\utils.py", line 119, in send_to_download
    translation = word['trs'][0]
<class 'TypeError'>: 'NoneType' object is not subscriptable

**Comment by vi3itor** [comment]
Моя ошибка, сейчас исправлю и отпишусь.

**Comment by vi3itor** [comment]
Обновитесь, перезапустите Анки и попробуйте ещё раз. 
Извините, что приходится делать несколько раз, но без примера слова (или фразы), на котором появляется ошибка, приходится обновляться вслепую :)

**Comment by vbutaev** [comment]
да, все получилось) спасибо большое за вашу работу, очень полезный плагин!

**Comment by vi3itor** [comment]
Отлично!
