### ISSUE TITLE
Can't import new words last few days

### ISSUE THREAD

**Issue by mvmalyi** [vi3itor/lingualeoanki#6]
After trying to import words I only receive a message "No words to import". I am afraid it is somehow related to changes on the server of Lingualeo.

**Comment by vi3itor** [comment]
Thanks! Yes, they changed the API for requesting the words. I'll try to fix the add-on in the upcoming days.

**Comment by mvmalyi** [comment]
Can’t wait! This tool is really useful. Thank you a lot :)

Sincerely yours, Max Malyi.

On Jul 28, 2019, at 4:35 PM, Victor Khaustov <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! Yes, they changed the API for requesting the words. I'll try to fix the add-on in the upcoming days.

**Comment by vi3itor** [comment]
Hi! Fixed the add-on, please update it and **restart Anki** for changes to take effect. Currently, context is not loaded, because of changes in API, but I will fix it later when they finish with experiments.

**Comment by mvmalyi** [comment]
Thank you for informing us 👍

**Comment by vi3itor** [comment]
By the way, I noticed that the website doesn't show all my words correctly: e.g., 6 months ago I added 64 words, but when I count them - there are only 58. I hope they will fix it soon because add-on also can not download missing words :)

**Comment by mvmalyi** [comment]
Sometimes I can’t really understand what they are doing, cus it seems like the service has a lot of bugs recently.

**Comment by dmitriimi** [comment]
I have the same problem
