### ISSUE TITLE
Got error on import all words 

### ISSUE THREAD

**Issue by vadeam** [vi3itor/lingualeoanki#7]
Hi.
After logged in with lingualeo accounts, I tried to import all words but got a popup with message  Error: ("'NoneType' object is not subscriptable",).
Anki version:
Version 2.1.11 (3cf770c7)
Qt 5.12.1 PyQt 5.11.3
System:
Darwin workstation.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by dtozik** [comment]
I have the same issue

There's been an unexpected error. Please copy the error message and create a new issue on GitHub (https://github.com/vi3itor/lingualeoanki/issues/new). Error: ("'NoneType' object is not subscriptable",)

**Comment by vi3itor** [comment]
Hi! 
Fixed the add-on, please update it and **restart Anki** for changes to take effect. Currently, context is not loaded, because of changes in API, but I will fix it later when they finish with experiments.

**Comment by vadeam** [comment]
Great! I have imported 1457 cards with their images and audio except few ones. Everything went smoothly.
Thank you very much for so quick fix.
