### ISSUE TITLE
No words to download

### ISSUE THREAD

**Issue by dmitriimi** [vi3itor/lingualeoanki#9]
У меня одного так?
I am alone?

**Comment by vi3itor** [comment]
API не менялся с последнего апдейта. Пробовали обновить дополнение? 
Чтобы обновить дополнение в Anki 2.1.x перейдите в "Инструменты" (Tools) > "Дополнения" (Add-ons). Выберите название дополнения и кликните на "Проверить обновления" (Check for updates). Нажмите "Да" для обновления и **перезапустите** Anki, чтобы изменения вступили в силу.

**Comment by dmitriimi** [comment]
Да, пробовал, обновление последнее, версия Anki 2.1.15 (MacOS).

Но помогло сделать это — удалить и снова добавить некоторые слова в словарь на LingvoLeo и заработало, правда почему-то слово "ham" в словаре есть (как новое слово), а в анки не импортирует, ну ладно, это мелочи, так как вроде все остальное и другие слова если добавлять все импортирует отлично, спасибо за отклик!
